### ISSUE TITLE
Pledge modal's background appears transparent on STAGING

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1054]
![screen shot 2015-06-19 at 2 09 01 pm](https://cloud.githubusercontent.com/assets/2896608/8263115/d33490b0-168c-11e5-8431-c21fefa118ec.png)

**Comment by mmmavis** [comment]
uh, can't immediately think of a reason why this is occurring...

**Comment by mmmavis** [comment]
```css
&:after {
    content: "";
    position: absolute;
    width: 1000%;
    height: 1000%;
    top: 4rem;
    background: @white none repeat scroll 0% 0%;
    transform-origin: 50% 0 0;
    transform: rotate(45deg);
    z-index: -1;
    right: -500%;
}
```

**STAGING**
![screen shot 2015-06-19 at 2 14 46 pm](https://cloud.githubusercontent.com/assets/2896608/8263260/c4b31664-168d-11e5-88ab-0f2a2c26bd07.png)
background colour is rendered as "transparent" instead of `#FFF`... :eyes: 

**LOCALHOST**
![screen shot 2015-06-19 at 2 15 11 pm](https://cloud.githubusercontent.com/assets/2896608/8263261/c70de614-168d-11e5-88ea-7ab98b751a57.png)
