### ISSUE TITLE
Make a `sidebarColorizer` LESS mixin

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#173]
`less/styles.less` currently contains a lot of [DRY](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) violations in its sidebar-colorizing code:

```less
// TODO: These alternate sidebar colors could probably
// be simplified w/ some kind of LESS mixins or something.

.page.events .sidebar {
  background-color: @redSidebarColor;

  .sidebar-header .corner {
    fill: @redSidebarColor;
  }

  .sidebar-menu a:hover, .sidebar-menu a:focus {
    background-color: darken(@redSidebarColor, 10%);
  }

  .sidebar-menu a .glyphicon {
    color: lighten(@redSidebarColor, 15%);
  }
}

.page.teach-like-mozilla .sidebar {
  background-color: @purpleSidebarColor;

  .sidebar-header .corner {
    fill: @purpleSidebarColor;
  }

  .sidebar-menu a:hover, .sidebar-menu a:focus {
    background-color: darken(@purpleSidebarColor, 10%);
  }

  .sidebar-menu a .glyphicon {
    color: lighten(@purpleSidebarColor, 15%);
  }
}

// And on and on...
```

It would be a lot nicer if we had a less mixin so the above code looked something like this:

```less
.page.events .sidebar {
  .sidebarColorizer(@redSidebarColor);
}

.page.teach-like-mozilla .sidebar {
  .sidebarColorizer(@purpleSidebarColor);
}
```

I'm not super familiar w/ LESS's mixin syntax so I'm not sure if that's exactly what it'd look like, but hopefully you get the idea.

@mmmavis would you be interested in taking this one?
